### ISSUE TITLE
Any possibility to make this mod work on the Steam Deck? (Proton/SteamOS/Linux)

### ISSUE THREAD

**Issue by Senkudou** [EusthEnoptEron/arise-multiplayer#92]
I really enjoyed this mod when the game first came out. Ever since 2022 I pretty much only play my Steam games on the Steam Deck. So I just wanted to know if there's any possibility to get this to work on the Steam Deck?

I tried to see if I can get it working myself but no luck on my end unfortunately (I'm a still new to Proton and Linux so I'm not a guru in that regard)

I understand if that's a large ask but I figured I'd ask to see if there can be a way. 

@EusthEnoptEron just wanted to say thanks for this awesome mod. It legit was the reason I decided to play the game, otherwise I wouldn't have. So thank you so much.

**Comment by EusthEnoptEron** [comment]
Glad to hear you enjoyed the mod.

I'm afraid getting it to work with Steam Deck might be ... challenging. I had hoped it would just magically work, but it seems that's not the case.

I'd have to delve into the nitty & gritty of how Wine / Proton translates DLLs and how I can hook into them / find the memory addresses I need, and I don't currently have time or motivation for that. (I've made my multiplayer playthrough, which was the reason I created this mod in the first place, so I am  pretty much done with the game.)

I'll close the issue for now, but if anyone wants to take a look, feel free to reopen it. I can also provide any assistance if required.

**Comment by Rogus9999** [comment]
can you help me do it in for linux arco linux or proton me and a friend wants to become programmers I see this as a great opportunity, mainly for the coding gaming part since I wanted to make a perfect game maybe for unreal or any newer engine and if tales of graces f remastered doesn't comes out with coop will you do it for it also if so I am more than willingly to help. I still learning the process so any guidance and assistance it's most appreciated. My discord tag is rogussantdenipate add me if you want to talk more. Thanks sir @EusthEnoptEron

**Comment by SrShadowy** [comment]
# **The mod actually works!**  
*Originally tested on arch linux, but should work across all Wine/Proton setups with a simple tweak.*

---

## 🚨 **The Problem**  
Proton and Wine **prioritize their built-in `xinput1_3.dll`** from the Wine/Proton prefix instead of loading the mod's custom DLL from the game folder.  
➡️ **Result:** The mod never initializes.

---

## 🔧 **The Fix**  
Force Proton/Wine to load the mod's DLL using a **Wine DLL override**:

```bash
WINEDLLOVERRIDES="xinput1_3=n,b" 
```

This tells Wine:  
*"Use the **native DLL** (from the game folder) first, fall back to Proton/Wine's built-in version if missing."*

---

## 📥 **How to Apply**
### **Steam Instructions**
1. Open your Steam Library
2. Right-click the game > **Properties**
3. In **Launch Options**, paste:  
   ```bash
   WINEDLLOVERRIDES="xinput1_3=n,b" %command%
   ```

### **Lutris Instructions**
1. Open Lutris and select the game
2. Click the ⚙️ **Configure** icon
3. Go to **System Options**
4. Add environment variable:  
   - **Key:** `WINEDLLOVERRIDES`  
   - **Value:** `xinput1_3=n,b`

### **Heroic Launcher**  
*Untested but should work similarly via environment variables in game settings.*

---

## ⚠️ Alternative Fix (Not Recommended)  
A secondary method involves **patching the game's .exe** to reference a differently named DLL.  
*🔔 Use with caution – this approach may cause instability!*
```
🔸 May cause crashes
🔸 Breaks with game updates
🔸 Only for advanced users
```

---
## 🧪 The Result
✅ Mod functionality works as expected
⚠️ BUT with some performance caveats:
> Slow initialization: Mod takes longer to load
> Stuttering: Brief freezes when entering/exiting battles

_Works but may require tolerance for occasional hiccups during critical moments._

---
*Tested working on my setup.*
_If not works for u comment bellow_

---

![Image](https://github.com/user-attachments/assets/7c0de967-aec9-4330-bda6-7556da36b669)

**Comment by Rogus** [comment]
Thanks it works wonders now only needs to be tested against the steam deck version, but I get the feeling it would works as just it's on arch and its distros's based off it. thanks again mister Shadowy
@EusthEnoptEron @SrShadowy 
why not mark as solved @EusthEnoptEron thank you once again for this wonderful mod.
